/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PlacesPlaceIdRouteImport } from './routes/places.$placeId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users.index'
import { Route as AdminPlacesIndexRouteImport } from './routes/admin/places.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminPlacesAddRouteImport } from './routes/admin/places.add'
import { Route as AdminUsersUserIdUpdateRouteImport } from './routes/admin/users_.$userId.update'
import { Route as AdminPlacesPlaceIdUpdateRouteImport } from './routes/admin/places.$placeId.update'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlacesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PlacesPlaceIdRoute = PlacesPlaceIdRouteImport.update({
  id: '/$placeId',
  path: '/$placeId',
  getParentRoute: () => PlacesRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlacesIndexRoute = AdminPlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlacesAddRoute = AdminPlacesAddRouteImport.update({
  id: '/places/add',
  path: '/places/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdUpdateRoute = AdminUsersUserIdUpdateRouteImport.update({
  id: '/users_/$userId/update',
  path: '/users/$userId/update',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlacesPlaceIdUpdateRoute =
  AdminPlacesPlaceIdUpdateRouteImport.update({
    id: '/places/$placeId/update',
    path: '/places/$placeId/update',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/places': typeof PlacesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/api/upload': typeof ApiUploadRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/admin/places/add': typeof AdminPlacesAddRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/places/$placeId/update': typeof AdminPlacesPlaceIdUpdateRoute
  '/admin/users/$userId/update': typeof AdminUsersUserIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/api/upload': typeof ApiUploadRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/admin': typeof AdminIndexRoute
  '/places': typeof PlacesIndexRoute
  '/admin/places/add': typeof AdminPlacesAddRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/places': typeof AdminPlacesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/places/$placeId/update': typeof AdminPlacesPlaceIdUpdateRoute
  '/admin/users/$userId/update': typeof AdminUsersUserIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/places': typeof PlacesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/api/upload': typeof ApiUploadRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/admin/places/add': typeof AdminPlacesAddRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/places/$placeId/update': typeof AdminPlacesPlaceIdUpdateRoute
  '/admin/users_/$userId/update': typeof AdminUsersUserIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/map'
    | '/places'
    | '/settings'
    | '/dashboard'
    | '/admin/categories'
    | '/admin/gallery'
    | '/api/upload'
    | '/places/$placeId'
    | '/admin/'
    | '/places/'
    | '/admin/places/add'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/admin/places/'
    | '/admin/users/'
    | '/admin/places/$placeId/update'
    | '/admin/users/$userId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map'
    | '/settings'
    | '/dashboard'
    | '/admin/categories'
    | '/admin/gallery'
    | '/api/upload'
    | '/places/$placeId'
    | '/admin'
    | '/places'
    | '/admin/places/add'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/admin/places'
    | '/admin/users'
    | '/admin/places/$placeId/update'
    | '/admin/users/$userId/update'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/admin'
    | '/login'
    | '/map'
    | '/places'
    | '/settings'
    | '/_layout/dashboard'
    | '/admin/categories'
    | '/admin/gallery'
    | '/api/upload'
    | '/places/$placeId'
    | '/admin/'
    | '/places/'
    | '/admin/places/add'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/admin/places/'
    | '/admin/users/'
    | '/admin/places/$placeId/update'
    | '/admin/users_/$userId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PlacesRoute: typeof PlacesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/places/$placeId': {
      id: '/places/$placeId'
      path: '/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof PlacesPlaceIdRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/places/': {
      id: '/admin/places/'
      path: '/places'
      fullPath: '/admin/places/'
      preLoaderRoute: typeof AdminPlacesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/places/add': {
      id: '/admin/places/add'
      path: '/places/add'
      fullPath: '/admin/places/add'
      preLoaderRoute: typeof AdminPlacesAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users_/$userId/update': {
      id: '/admin/users_/$userId/update'
      path: '/users/$userId/update'
      fullPath: '/admin/users/$userId/update'
      preLoaderRoute: typeof AdminUsersUserIdUpdateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/places/$placeId/update': {
      id: '/admin/places/$placeId/update'
      path: '/places/$placeId/update'
      fullPath: '/admin/places/$placeId/update'
      preLoaderRoute: typeof AdminPlacesPlaceIdUpdateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPlacesAddRoute: typeof AdminPlacesAddRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminPlacesIndexRoute: typeof AdminPlacesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminPlacesPlaceIdUpdateRoute: typeof AdminPlacesPlaceIdUpdateRoute
  AdminUsersUserIdUpdateRoute: typeof AdminUsersUserIdUpdateRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPlacesAddRoute: AdminPlacesAddRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminPlacesIndexRoute: AdminPlacesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminPlacesPlaceIdUpdateRoute: AdminPlacesPlaceIdUpdateRoute,
  AdminUsersUserIdUpdateRoute: AdminUsersUserIdUpdateRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PlacesRouteChildren {
  PlacesPlaceIdRoute: typeof PlacesPlaceIdRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesPlaceIdRoute: PlacesPlaceIdRoute,
  PlacesIndexRoute: PlacesIndexRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PlacesRoute: PlacesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
